#ifndef LOGGING_H
#define LOGGING_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(LOG_MAINWINDOW);
Q_DECLARE_LOGGING_CATEGORY(LOG_ABOUT_DIALOG);
Q_DECLARE_LOGGING_CATEGORY(LOG_PLUGIN);
Q_DECLARE_LOGGING_CATEGORY(LOG_WEBVIEW);
Q_DECLARE_LOGGING_CATEGORY(LOG_HIGHLIGHTER);
Q_DECLARE_LOGGING_CATEGORY(LOG_EPUB);
Q_DECLARE_LOGGING_CATEGORY(LOG_MOBI);
Q_DECLARE_LOGGING_CATEGORY(LOG_PARSER);
Q_DECLARE_LOGGING_CATEGORY(LOG_METADATA);

#endif // LOGGING_H
