#ifndef YAMLCPP_GLOBAL_H
#define YAMLCPP_GLOBAL_H

#if defined(YAMLCPP_LIBRARY)
#  define YAMLCPPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define YAMLCPPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YAMLCPP_GLOBAL_H




